# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NutriFact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('servingSize', models.FloatField()),
                ('servingUM', models.CharField(max_length=4)),
                ('servingQuantity', models.FloatField()),
                ('servingQtdUm', models.CharField(max_length=4)),
                ('footNote', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NutriTable',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('componentID', models.CharField(max_length=60)),
                ('componentQuantity', models.FloatField()),
                ('componentUM', models.CharField(max_length=4)),
                ('dailyValues', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('manufacturer', models.CharField(max_length=60)),
                ('barcode', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='nutritable',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facts.Product'),
        ),
        migrations.AddField(
            model_name='nutrifact',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facts.Product'),
        ),
    ]
