# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-18 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutrifact',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='nutritable',
            old_name='index',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='nutritable',
            old_name='product_id',
            new_name='product',
        ),
    ]
