# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0002_auto_20170418_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='id',
            new_name='product_id',
        ),
    ]
