# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0003_auto_20170606_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='key',
        ),
    ]
